_target_: tasks.pendulum.HiddenDoublePendulum
name: DoublePendulum

# Physical dimensions
dim_xi: 2
dim_y: 4
dim_theta: 4

# ALINE target setup
embedding_type: theta
mask_type: ["all"]

n_selected_targets: null
predefined_masks: null
predefined_mask_weights: null
mask_index: null
attend_to: null

n_target_data: 0
n_target_theta: 4

# Initial context and candidate pool
n_context_init: 1
n_query_init: 200

# Scaling
design_scale: 1.0
outcome_scale: 1.0

# Sequential / non-exchangeable augmentation
include_time: true
normalize_time: true
max_T: ${T}
use_delta_y: true

# Simulator
dt: 0.05

device: ${device}
training: true