_target_: tasks.double_pendulum.HiddenDoublePendulum

name: DoublePendulum

dim_x: 2
dim_y: 4

embedding_type: theta
mask_type: ["all"]

n_selected_targets: null
predefined_masks: null
predefined_mask_weights: null
mask_index: null
attend_to: null

n_target_data: 0
n_target_theta: 4

n_context_init: 1
n_query_init: 200

dim_theta: 4
design_scale: 1.0
outcome_scale: 1.0

dt: 0.05
device: ${device}
training: true